Async App has been completed
NET16-Homeworks/HomeworkAsyncAndFileSystem pull request #3
Opened 2022-10-30 14:42 UTC by kricobelka

Добавление доп юзеров и адресов сделано очень изощренно))
но работает

Жду комментов :)

божеский  уровень пока не делала

2022-11-06 19:52 UTC, im-kborovik requested changes

2022-11-06 19:52 UTC, im-kborovik commented on AsyncWebApplication1/Controllers/HomeController.cs
> +            await Task.Delay(0);
эм.... а зачем тебе тут вообще асинхронность?) я же не говорил сделайте ВСЕ методы асинхронными))

2022-11-06 19:52 UTC, im-kborovik commented on AsyncWebApplication1/Controllers/HomeController.cs
> +            await Task.Delay(0);
смысл асинхронного программирования ожидать выполнения не Task.Delay(0), а другого асинхронного метода

2022-11-06 19:52 UTC, im-kborovik commented on AsyncWebApplication1/Helpers/UserHelper.cs
> +            return usersCity;
А что ж ты это не сделала с помощью Select и не привила это к ToList?

2022-11-06 19:52 UTC, im-kborovik commented on AsyncWebApplication1/Helpers/UserHelper.cs
> +                fs.Close();
поток сам закроется по окончании using

2022-11-06 19:52 UTC, im-kborovik commented on AsyncWebApplication1/Models/AddressModel.cs
> +        public int ?HouseNumber { get; set; }
Что это за вопросики? мало того, что они неправильно написаны (между типом и вопросом не ставится пробел), так они тут вообще не нужны.

2022-11-07 17:35 UTC, kricobelka commented on AsyncWebApplication1/Controllers/HomeController.cs
> +            await Task.Delay(0);
fixed

2022-11-07 17:36 UTC, kricobelka commented on AsyncWebApplication1/Helpers/UserHelper.cs
> +                fs.Close();
ок,  убрала) причина, по которой я поставила fs.close - у меня при запуске иногда выбивало сообщение "Приложение занято другим процессом", я поналепила fs.Close, помогало время от времени

2022-11-07 17:37 UTC, kricobelka commented on AsyncWebApplication1/Models/AddressModel.cs
> +        public int ?HouseNumber { get; set; }
а почему не нужны? вдруг у меня это не обязательные поля)

2022-11-07 17:42 UTC, kricobelka commented on AsyncWebApplication1/Controllers/HomeController.cs
> +            await Task.Delay(0);
да, сенсей)
подправила

2022-11-07 18:30 UTC, kricobelka commented on AsyncWebApplication1/Helpers/UserHelper.cs
> +            return usersCity;
fixed! сделала с помощью селекта,
посмотри пжл, правильно ли
пушаю изменения

2022-11-13 10:53 UTC, im-kborovik approved these changes

2022-11-13 10:53 UTC, closed without merging